### PR TITLE
Also kill url[rel="suggestions"] and generic search GET forms

### LINKED ISSUE #1: It just plain doesn't work
I've made a fork and tried to get it going again, but it appears that even if you remove the opensearch link elements, the search engine still gets added to Chrome. There might be some other completely different tactic which would work, but I'm not familiar enough with the Chrome extension API to think of one.

### PR DESCRIPTION
**Pull request by cxw42**
Incorporates everybody's changes up to this point, and appears to be working in my testing on Chrome 64.

Closes #1 
Closes #2 
Closes #3

### CODE REVIEW

**Comment by gregsadetsky** [comment]
Going to give it a test now (finally!), report back, and then hopefully go on to merge & deploy. More news soon.

**Comment by gregsadetsky** [comment]
Ok, this is wonderful!! I ran through a list of 142 sites that add custom search engine and only one of them ended up not being detected by this branch -- DuckDuckGo! Pretty funny, right? :-)

This is great. I do want to say that I'm a little bit wary of the textarea-adding approach, simply because that might lead to some sites/forms breaking (those sites that expect a very specific list of inputs submitted through its forms). On the other hand, I feel like this a (very) specialized extension, so hopefully we can go with this approach for now, and see if there are issues with it.

Fantastic! Last thing would be to comment out the console.* calls, which I'll do in a subsequent commit.

I'll let everyone now once this is deployed (w00t)! For now, merging this.

Congrats &&& Huge Thanks to everyone for the great work. And your almost limitless patience. Thanks for believing. :-)

Cheers

**Comment by snowbound** [comment]
Well I downloaded this commit last week and just checked here. Youtube, finance.google.com and https://forum.glasswire.com/search?q=%s all showed up in my Search engine. 

This may be moot though as I am seriously thinking of switching to using Firefox. Getting fed up with Google products and their lack of contacting anyone wrt to security issues re another product.

**Comment by gregsadetsky** [comment]
hey @snowbound I just tried youtube.com, finance.google.com and forum.glasswire.com and none of them were added as search engines.

the 0.0.2 update in the chrome extension store is still propagating (it may take up to 24 hours) -- would you mind testing it there (i.e., downloading the new version from the official store), or trying this code again directly from the master branch (into which the new code has been merged)?

thank you!

**Comment by Songworks** [comment]
Awesome work guys, thank you so very much!

File: src/content.js [hunk 1]
```diff
@@ -1,7 +1,79 @@
...
+  function (it) {
+   it.removeAttribute('rel');
+   console.info({"Spoiled by rel removal": it});
+  }
+ );
+
+ // Chrome autodetection, https://www.chromium.org/tab-to-search #2
+ // Can't test for form[method="get" i] here because bleepingcomputer.com's
+ // search form doesn't have an express @method
+ document.querySelectorAll('form').forEach(spoilFormGet);
```
Comment (ap) [inline src/content.js]:
````js
document.querySelectorAll('form[method="get" i], form:not([method])').forEach(spoilFormGet);
````

**Comment by cxw42** [comment]
>Ok, this is wonderful!! I ran through a list of 142 sites that add custom search engine and only one of them ended up not being detected by this branch -- DuckDuckGo! Pretty funny, right? :-)

@gregsadetsky I checked, and as far as I can tell, DDG creates its search form using JS after the page loads.  I think we'll have to accept a DDG entry in the search-engine list :) .

If you visit DDG in lynx, you get redirected to https://duckduckgo.com/lite/ instead.  `/lite/` uses a POST, so we don't have to worry about that one.

File: src/content.js (hunk 1 above)
Comment (cxw42) [reply src/content.js]: Nice!  That does appear to do the job on bleepingcomputer.  Are you going to put it in a PR?  If not, I will.

File: src/content.js [hunk 2]
```diff
@@ -1,7 +1,79 @@
...
+
+ if(elem.querySelector(':scope input[type="password" i]')) return;
+ if(elem.querySelector(':scope input[type="file" i]')) return;
+ if(elem.querySelector(':scope textarea')) return;
+
+ // Add a <textarea> - unlike <input>, it doesn't block implicit submission
+ // per https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/
+ var newelem;
+ newelem = document.createElement('textarea');
+ newelem.name = 'chrome_dont_add_custom_search_engines_srsly';
```
Comment (zessx) [inline src/content.js]: Honestly?   
Replacing an annoying behavior by another one is *not* an improvement...

Comment (gregsadetsky) [reply src/content.js]: hey @zessx , I agree that adding a textarea is a bit of an "aggressive" method, although it does help in stopping new search engines from being added

do you feel like this approach might "break" many web forms? or is it more a consideration of "do as little harm to the DOM as possible"?

I'm wondering if we couple separate the form detection/textarea adding and mark it as an "advanced" feature which could be disabled by default

thoughts? @cxw42 ?

Comment (cxw42) [reply src/content.js]: The [autodetection](https://www.chromium.org/tab-to-search), part 2, is actually very effective at automatically adding most search boxes :/ .  No surprise, since that's what it's supposed to do! :)  Take out the `<textarea>`, and you're right back to where the extension was before.

My first try was adding an `onsubmit` script, since the autodetection page mentions onsubmit scripts aren't autodetected.  However, that didn't work.  I am guessing that so many forms now have onsubmit that the Chromium team removed that check, and just didn't update the documentation page.

My second try was to add a hidden `<input>`, but that prevents GitHub's search forms from working (pressing Enter no longer submits when there are multiple `<input>` elements).

@zessx If you can show me a better way that also works, please do!  I have started watching this repo and will be looking forward to your PR ;) .

Comment (zessx) [reply src/content.js]: I was more upset by the 12-miles-long GET parameter name than by the addition of a `textarea`.   

We may not have a better way right know, and I'm fine with it, but at least let's choose a shorter name. I work a lot with URLs (on search engines, specifically), and to get `&chrome_dont_add_custom_search_engines_srsly=` in all of them is a big no.   
What about `cdacse`, or `dacse`?

On the `textarea` itself, I think it *may* interferes with abstract APIs (taking into account every sent parameters). Even if this interference is a proof that this kind of APIs are highly vulnerable, it could be a good idea to get a whitelist in the extension.

Comment (gregsadetsky) [reply src/content.js]: I agree that the long GET URLs are "visually" annoying, and can get in the way of testing/development.

I think that one good side about using a unique name for that parameter is that it is highly google-able, and won't risk conflicting with internal parameters which may use names like `cdacse`.

Having a whitelist seems like a very good idea. Something akin to ad blockers where clicking the extension icon would allow you turning it on/off for the domain, and greying out the icon when it detects that it's on a whitelisted site..?

Comment (zessx) [reply src/content.js]: I think we can find something almost unique, *and* shorter than 43 chars :)

What about a combination of a little name, and a time-related number?
This has a really low level of collision, and in the worst case it would work again later.

Time-related part | Validity | Collision level | Exemple
---|---|---|---
minutes | 1 minute | medium | `cse09` 
hour+minutes | 1 minute | low | `cse1509` 
6-digit timestamp | 3 hours~ | low | `cse152173`

**Comment by gregsadetsky** [comment]
I think that adding a time related number defeats the goal of having a unique name (easy to find using google)

I think that we should prioritize the whitelist feature first. It will get rid of the problem for those that are witnessing the GET url "pollution" (while pointing out, using its long but obvious name, where the extra GET arg is coming from).

We can then try to come up with a good naming scheme (supposedly one of the two complicated things in CS) :-)

File: src/content.js (hunk 2 above)
Comment (ap) [reply src/content.js]: Does it have to be sent in order to foil Chrome’s detection? ’Cause you can prevent it from being sent by setting the `disabled` property to true.

Comment (gregsadetsky) [reply src/content.js]: good idea, @ap -- I just tried disabling the textarea and unfortunately that lets the search engine be added.

Comment (cxw42) [reply src/content.js]: @zessx Thanks for clarifying what you were referring to in your first message.  I agree with the comment out-of-line from @gregsadetsky setting whitelist as a higher priority than name-change.

I haven't been a server admin for a long time, but I would think being able to easily identify something weird in my logs would make me happy.  And the existing name is already indexed on Google :) .

Comment (cxw42) [reply src/content.js]: @gregsadetsky You beat me to it :) .  I also just tried the same - bleepingcomputer is added with `<textarea disabled>`.

Comment (ap) [reply src/content.js]: Hmm. Then maybe like this?

````html
<input type="radio" name="chrome_dont_add_custom_search_engines_srsly" tabindex="-1" style="display: none !important">
````

The trick to this is that a `radio` (or `checkbox`) without a `checked` attribute doesn’t become part of the URL… so this has the same effect as marking it `disabled` – but hopefully while still foiling Chrome’s detection.

The other attributes try to make it as unobtrusive as possible. Submitting the form using Enter still works for me if I use the DOM inspector to add such an `<input>` to the GitHub search form at the top of the page, at least.

Comment (cxw42) [reply src/content.js]: @ap Good idea.  Unfortunately, my [test branch](https://github.com/cxw42/chrome-dont-add-custom-search-engines/tree/radio) fails on bleepingcomputer and on gcmap.com.

Comment (gregsadetsky) [reply src/content.js]: digging around, I found [ParseIfNecessary](https://github.com/chromium/chromium/blob/master/components/search_engines/template_url.cc#L811) which counts the "search terms" found in the URL and sets the bool `supports_replacements_` which determines if the URL is then used to create a new custom search engine or not.

this would confirm that we do need to send more than 1 value to foil the search engine detection

Comment (cxw42) [reply src/content.js]: Good find.  Wild thought - what about an astral or private-use field name?  If we assume sites are 8-bit clean unless whitelisted, we could use U+10cda U+1005e or something not yet assigned.  In the query-string, that will work out as escaped utf8 bytes.

Comment (gregsadetsky) [reply src/content.js]: I'd err on the side of caution / sites not necessarily being ready for this kind of input? + the current google-ability of the name used for the textarea seems like a good idea

love the idea, just unsure of repercussions...!
